#pragma once

// Mouse codes
#define TERRA_MOUSE_BUTTON_1         0x01
#define TERRA_MOUSE_BUTTON_2         0x02
#define TERRA_MOUSE_BUTTON_4         0x03		// VK_CANCEL
#define TERRA_MOUSE_BUTTON_3         0x04
#define TERRA_MOUSE_BUTTON_5         0x07		// Undefined
#define TERRA_MOUSE_BUTTON_6         0x07
#define TERRA_MOUSE_BUTTON_7         0x05		// X1
#define TERRA_MOUSE_BUTTON_8         0x06		// X2 
#define TERRA_MOUSE_BUTTON_LAST      TERRA_MOUSE_BUTTON_7
#define TERRA_MOUSE_BUTTON_NEXT	  TERRA_MOUSE_BUTTON_8
#define TERRA_MOUSE_BUTTON_LEFT      TERRA_MOUSE_BUTTON_1
#define TERRA_MOUSE_BUTTON_RIGHT     TERRA_MOUSE_BUTTON_2
#define TERRA_MOUSE_BUTTON_MIDDLE    TERRA_MOUSE_BUTTON_3
